-- Run this script in the Supabase SQL Editor to set up your tables
-- The foreign keys automatically handle cascading deletes!

CREATE TABLE IF NOT EXISTS quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  difficulty TEXT DEFAULT 'easy',
  time_limit INTEGER DEFAULT 0,
  pass_percent INTEGER DEFAULT 50,
  show_explanation TEXT DEFAULT 'after_quiz',
  status TEXT DEFAULT 'Draft',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option TEXT NOT NULL,
  explanation TEXT,
  difficulty TEXT
);

CREATE TABLE IF NOT EXISTS attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE,
  user_id TEXT,
  user_name TEXT,
  score INTEGER DEFAULT 0,
  total INTEGER DEFAULT 0,
  time_taken INTEGER DEFAULT 0,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
